<h1 class="text-center"><?php echo CONFIG_SITE_TITLE ?></h1>


<div style="max-width: 700px; margin:auto;">

<!--Les trois petits boutons en bas du carousel...
On fait une boucle foreach pour chaque pic-->
<div id="homeCarousel" class="carousel slide" data-bs-touch="true">
  <div class="carousel-indicators">
    <!--La variable $key ici permet d'avoir un décompte 0,1,2 pour faire fonctionner le slider-->
    <?php foreach($pictures as $key => $pic): ?>
    <button type="button" data-bs-target="#homeCarousel" data-bs-slide-to="<?= $key ?>" <?php if ($key===array_key_first($pictures)) echo 'class="active" aria-current="true"'; ?> aria-label="Slide <?= $key+1 ?>"></button>
    <?php endforeach ?>
    <!--fin de la boucle foreach des boutons du bas du carousel-->
</div>

<!--div du contenu du carousel-->
  <div class="carousel-inner">
  <!--deuxième boucle foreach pour afficher chaque pic avec sa src title et description-->
  <?php foreach($pictures as $key => $pic): ?>
    <div class="carousel-item <?php if ($key===array_key_first($pictures)) echo 'active' ?>">
      <img src="<?= $pic['src'] ?>" class="d-block w-100" alt="<?= $pic['title'] ?>">
      <div class="carousel-caption d-none d-md-block">
        <h5><?= $pic['title'] ?></h5>
        <p><?= $pic['description'] ?></p>
      </div>
    </div>
    <?php endforeach ?>
  </div>

  <!--Flèche de gauche-->
  <button class="carousel-control-prev" type="button" data-bs-target="#homeCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>

  <!--Flèche de droite-->
  <button class="carousel-control-next" type="button" data-bs-target="#homeCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

</div>

</div> 