<h1> Connexion </h1>

<form method="POST">

  <div class="input-group mb-3">
    <span class="input-group-text" id="inputGroup-sizing-default">Pseudo</span>
    <input type="text" class="form-control" aria-label="Sizing example input"
      aria-describedby="inputGroup-sizing-default" name="pseudo">
  </div>

  <div class="input-group mb-3">
    <span class="input-group-text" id="inputGroup-sizing-default">Mot de passe</span>
    <input type="text" class="form-control" aria-label="Sizing example input"
      aria-describedby="inputGroup-sizing-default" name="password">
  </div>

  <input class="btn btn-primary" type="submit" value="Connexion" name="connexion" id="connect">

</form>

<br>

<a href="http://localhost/sites/MVC_PHP/index.php?page=inscription">
  <button class="btn btn-outline-info">
    Pas de compte ? Inscris toi 😊
  </button>
</a>