<form method="POST">

  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" name="title" placeholder="Title">
  </div>

  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <input type="text" class="form-control" name="description" placeholder="Description">
  </div>

  <div class="mb-3">
    <label for="src" class="form-label">Source</label>
    <input type="text" class="form-control" name="src" placeholder="URL Source">
  </div>

  <div class="mb-3">
    <label for="author" class="form-label">Author</label>
    <input type="text" class="form-control" name="author" placeholder="Author">
  </div>

  <div class="col-3">
    <button type="submit" class="btn btn-primary" name="submit">Submit</button>
  </div>

</form>