<h1 class="mb-3 text-center">
    <?= $pic['title'] ?>
</h1>

<section class="row">
    <div class="col">
        <img src="<?= $pic['src'] ?>" alt="<?= $pic['title'] ?>" class="img-fluid">
    </div>
    <div class="col-12 mt-3">
        <p>
            <?= $pic['description'] ?>
        </p>
    </div>
    <div class="col-6 mt-3 fst-italic font-weight-light">
        <p>Created At:
            <?= $pic['created_at'] ?> | Updated At:
            <?= $pic['updated_at'] ?>
        </p>
    </div>
    <div class="col-6 mt-3 fst-italic font-weight-light">
        <p>
            <?= $pic['author'] ?>
        </p>
    </div>
</section>

<form method="POST" class="row">

    <div class="col-sm-8">
        <div class="input-group">
            <span class="input-group-text">Commentaire</span>
            <textarea class="form-control" aria-label="With textarea" name="text"></textarea>
        </div>
    </div>

    <div class="col-sm-4">
        <input class="btn btn-primary" type="submit" value="postez" name="submit">
    </div>

</form>

<br>

<?php

foreach ($comments as $comment): ?>
    <p>
        <?= $comment['user_pseudo']; ?>
    </p>
    <p>
        <?= $comment['comment_text']; ?>
    </p>


<?php endforeach ?>