<h1>Inscription</h1>

<br>

<form method="POST">

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">@</span>
  </div>
  <input type="text" class="form-control" placeholder="Pseudo" aria-label="Username" aria-describedby="basic-addon1" name="pseudo">
</div>


<div class="input-group">
  <div class="input-group-prepend">
    <span class="input-group-text" id="">Nom et prénom</span>
  </div>
  <input type="text" class="form-control" name="nom">
  <input type="text" class="form-control" name="prenom">
</div>

<br>

<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Adresse mail" aria-label="Recipient's username" aria-describedby="basic-addon2" name="mail">
  <div class="input-group-append">
    <span class="input-group-text" id="basic-addon2">@exemple.com</span>
  </div>
</div>

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">Mot de passe</span>
  </div>
  <input type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1" name="password">
</div>

<br>

<input class="btn btn-primary" type="submit" value="submit" name="submit">

</form>